#    docker build -t crowdcountcr.azurecr.io/crowdcount_imagecontrol:latest  .
#    az acr login --name crowdcountcr
#    docker push crowdcountcr.azurecr.io/crowdcount_imagecontrol:latest
#    kubectl apply -f .\CrowdCountImageControl.yaml


on:
  push:
name: hashito
jobs:
  test:
    name: CI Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: crowdcountcr.azurecr.io
          repository: testtarou
          tags: latest
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: set image deployment/testtarou testtarouimg=crowdcountcr.azurecr.io/testtarou:latest